document.addEventListener("DOMContentLoaded",()=>{const slider={slides:document.querySelectorAll(".slide"),dots:document.querySelectorAll(".dot"),prevBtn:document.querySelector(".arrow.prev"),nextBtn:document.querySelector(".arrow.next"),currentSlide:0,slideInterval:null,init:function(){if(!this.slides.length)return;if(this.dots.length){this.dots.forEach((dot,index)=>{dot.addEventListener("click",()=>{this.goToSlide(index)})})}
if(this.prevBtn){this.prevBtn.addEventListener("click",()=>this.prevSlide())}
if(this.nextBtn){this.nextBtn.addEventListener("click",()=>this.nextSlide())}
this.startAutoSlide();const sliderElement=document.querySelector(".hero-slider");if(sliderElement){sliderElement.addEventListener("mouseenter",()=>this.pauseAutoSlide());sliderElement.addEventListener("mouseleave",()=>this.startAutoSlide())}
document.addEventListener("keydown",(e)=>{if(e.key==="ArrowLeft"){this.prevSlide()}else if(e.key==="ArrowRight"){this.nextSlide()}});this.preloadNextSlide()},goToSlide:function(index){if(index<0||index>=this.slides.length||index===this.currentSlide)
return;this.slides[this.currentSlide].classList.remove("active");this.slides[index].classList.add("active");if(this.dots.length){this.dots[this.currentSlide].classList.remove("active");this.dots[index].classList.add("active")}
this.currentSlide=index;this.preloadNextSlide()},nextSlide:function(){const next=(this.currentSlide+1)%this.slides.length;this.goToSlide(next)},prevSlide:function(){const prev=(this.currentSlide-1+this.slides.length)%this.slides.length;this.goToSlide(prev)},startAutoSlide:function(){this.pauseAutoSlide();this.slideInterval=setInterval(()=>{this.nextSlide()},5000)},pauseAutoSlide:function(){if(this.slideInterval){clearInterval(this.slideInterval);this.slideInterval=null}},preloadNextSlide:function(){const nextIndex=(this.currentSlide+1)%this.slides.length;const nextSlide=this.slides[nextIndex];if(nextSlide){const img=nextSlide.querySelector("img");if(img&&img.dataset.src&&!img.src){img.src=img.dataset.src}
const source=nextSlide.querySelector("source");if(source&&source.dataset.src&&!source.srcset){source.srcset=source.dataset.src}}},};slider.init();if("IntersectionObserver" in window){const lazyImages=document.querySelectorAll('img[loading="lazy"]');const imageObserver=new IntersectionObserver((entries,observer)=>{entries.forEach((entry)=>{if(entry.isIntersecting){const img=entry.target;img.src=img.dataset.src||img.src;observer.unobserve(img)}})});lazyImages.forEach((img)=>{imageObserver.observe(img)})}
const lazyIframes=document.querySelectorAll('iframe[loading="lazy"]');if("IntersectionObserver" in window){const iframeObserver=new IntersectionObserver((entries,observer)=>{entries.forEach((entry)=>{if(entry.isIntersecting){const iframe=entry.target;if(iframe.dataset.src){iframe.src=iframe.dataset.src;iframe.removeAttribute("data-src")}
observer.unobserve(iframe)}})});lazyIframes.forEach((iframe)=>{iframeObserver.observe(iframe)})}else{lazyIframes.forEach((iframe)=>{if(iframe.dataset.src){iframe.src=iframe.dataset.src;iframe.removeAttribute("data-src")}})}
function throttle(func,delay){let lastCall=0;return(...args)=>{const now=new Date().getTime();if(now-lastCall<delay){return}
lastCall=now;return func(...args)}}
document.querySelectorAll('a[href^="#"]').forEach((anchor)=>{anchor.addEventListener("click",function(e){e.preventDefault();const targetId=this.getAttribute("href");if(targetId==="#")return;const targetElement=document.querySelector(targetId);if(targetElement){targetElement.scrollIntoView({behavior:"smooth",block:"start",})}})});const sections=document.querySelectorAll("section[id]");const navLinks=document.querySelectorAll(".nav-links a");const highlightNavigation=throttle(()=>{const scrollPosition=window.scrollY+100;sections.forEach((section)=>{const sectionTop=section.offsetTop;const sectionHeight=section.offsetHeight;const sectionId=section.getAttribute("id");if(scrollPosition>=sectionTop&&scrollPosition<sectionTop+sectionHeight){navLinks.forEach((link)=>{link.classList.remove("active");if(link.getAttribute("href")===`#${sectionId}`){link.classList.add("active")}})}})},100);window.addEventListener("scroll",highlightNavigation);if("IntersectionObserver" in window){const animatedElements=document.querySelectorAll(".feature-box, .testimonial-box, .pricing-box");const animationObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("animated");animationObserver.unobserve(entry.target)}})},{threshold:0.1});animatedElements.forEach((element)=>{animationObserver.observe(element)})}})